modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "angelring"
version = "${version}"
displayName = "angelring"
authors = "DenisMasterHerobrine"
description = '''
Angel Ring 3 is a mod which adds a new ring into Minecraft. This ring allows you to fly like in a creative mode. Inspired by Extra Utilities 2.
'''
#logoFile = ""

[[dependencies.angelring]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.angelring]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "angelring.mixins.json"
